name: Python

on:
  push:

jobs:
  Dependencies:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [ 3.9, "3.10" ]
    steps:
      - uses: actions/checkout@v3
      - name: Install Poetry
        run: pipx install poetry==1.1.13
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
          cache: 'poetry'
      - name: Install dependencies
        run: |
          poetry env use ${{ matrix.python }}
          poetry install
  Linting:
    needs: [Dependencies]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [ 3.9, "3.10" ]

    steps:
      - uses: actions/checkout@v3
      - name: Install Poetry
        run: pipx install poetry==1.1.13
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
          cache: 'poetry'
      - name: Install dependencies
        run: |
          poetry env use ${{ matrix.python }}
          poetry install
      - name: Run Flake8
        run: poetry run flake8
  Typing:
    needs: [Dependencies]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [ 3.9, "3.10" ]

    steps:
      - uses: actions/checkout@v3
      - name: Install Poetry
        run: pipx install poetry==1.1.13
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
          cache: 'poetry'
      - name: Install dependencies
        run: |
          poetry run python --version
          poetry env use ${{ matrix.python }}
          poetry install
          poetry run python --version
      - name: Run Mypy
        run: poetry run mypy --python-version=${{ matrix.python }}
