name: Python

on:
  push:

jobs:
  Dependencies:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [ 3.9, "3.10" ]
    steps:
      - uses: actions/checkout@v3
      - name: Install Poetry
        run: pipx install poetry==1.1.13
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python }}
          cache: 'poetry'
      - name: Install dependencies
        run: |
          poetry env use ${{ matrix.python }}
          poetry install
  Linting:
    needs: [Dependencies]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [ 3.9, "3.10" ]

    steps:
      - uses: actions/checkout@v3
      - name: Install Poetry
        run: pipx install poetry==1.1.13
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python }}
          cache: 'poetry'
      - name: Install dependencies
        run: |
          poetry env use ${{ matrix.python }}
          poetry install
      - name: Activate Virtual Environment
        run: source .venv/bin/activate
      - name: Run Flake8
        run: python -m flake8
  Typing:
    needs: [Dependencies]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [ 3.9, "3.10" ]

    steps:
      - uses: actions/checkout@v3
      - name: Install Poetry
        run: pipx install poetry==1.1.13
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python }}
          cache: 'poetry'
      - name: Install dependencies
        run: |
          poetry env use ${{ matrix.python }}
          poetry install
      - name: Activate Virtual Environment
        run: source .venv/bin/activate
      - name: Run Mypy
        run: python -m mypy --python-version=${{ matrix.python }}
